In [211]:
# Project 1
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

In [212]:
# This frame uses get to obtain the HTML file and printed it so we can see what we were working with
# Headers to make sure requests actually works every time
header = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'
    }
res = requests.get("https://www.spaceweatherlive.com/en/solar-activity/top-50-solar-flares.html", headers = header)
print(res.status_code)
soup = BeautifulSoup(res.content, "html.parser")
# print (soup.prettify)

200

In [213]:
# This frame finds the table and loads it into pandas for formatting

# Find the table 
table = soup.find('table')

# Load it into pandas making sure all formatted as string
data = pd.read_html(str(table))
data = data[0]
data.rename(columns={'Unnamed: 0': 'Rank', 'Unnamed: 1': 'X_class', 'Unnamed: 2': 'Date', 'Region': 'Region', 
                       'Start': 'Start', 'Maximum': 'Max', 'End':'End'}, inplace=True)
# Printed status code bc Kernel was being dumb with requests. Sometimes throws 403 and have to wait it out
print(res.status_code)
data
# End of step 1

200

    Rank X_class        Date  Region  Start    Max    End         Unnamed: 7
0      1    X28+  2003/11/04     486  19:29  19:53  20:06  MovieView archive
1      2    X20+  2001/04/02    9393  21:32  21:51  22:03  MovieView archive
2      3  X17.2+  2003/10/28     486  09:51  11:10  11:24  MovieView archive
3      4    X17+  2005/09/07     808  17:17  17:40  18:03  MovieView archive
4      5   X14.4  2001/04/15    9415  13:19  13:50  13:55  MovieView archive
5      6     X10  2003/10/29     486  20:37  20:49  21:01  MovieView archive
6      7    X9.4  1997/11/06    8100  11:49  11:55  12:01  MovieView archive
7      8    X9.3  2017/09/06    2673  11:53  12:02  12:10  MovieView archive
8      9      X9  2006/12/05     930  10:18  10:35  10:45  MovieView archive
9     10    X8.3  2003/11/02     486  17:03  17:25  17:39  MovieView archive
10    11    X8.2  2017/09/10    2673  15:35  16:06  16:31  MovieView archive
11    12    X7.1  2005/01/20     720  06:36  07:01  07:26  MovieView archive
12    13    X6.9  2011/08/09    1263  07:48  08:05  08:08  MovieView archive
13    14    X6.5  2006/12/06     930  18:29  18:47  19:00  MovieView archive
14    15    X6.2  2005/09/09     808  19:13  20:04  20:36  MovieView archive
15    16    X6.2  2001/12/13    9733  14:20  14:30  14:35  MovieView archive
16    17    X5.7  2000/07/14    9077  10:03  10:24  10:43  MovieView archive
17    18    X5.6  2001/04/06    9415  19:10  19:21  19:31  MovieView archive
18    19    X5.4  2012/03/07    1429  00:02  00:24  00:40  MovieView archive
19    20    X5.4  2005/09/08     808  20:52  21:06  21:17  MovieView archive
20    21    X5.4  2003/10/23     486  08:19  08:35  08:49  MovieView archive
21    22    X5.3  2001/08/25    9591  16:23  16:45  17:04  MovieView archive
22    23    X4.9  2014/02/25    1990  00:39  00:49  01:03  MovieView archive
23    24    X4.9  1998/08/18    8307  22:10  22:19  22:28       View archive
24    25    X4.8  2002/07/23      39  00:18  00:35  00:47  MovieView archive
25    26      X4  2000/11/26    9236  16:34  16:48  16:56  MovieView archive
26    27    X3.9  2003/11/03     488  09:43  09:55  10:19  MovieView archive
27    28    X3.9  1998/08/19    8307  21:35  21:45  21:50       View archive
28    29    X3.8  2005/01/17     720  06:59  09:52  10:07  MovieView archive
29    30    X3.7  1998/11/22    8384  06:30  06:42  06:49  MovieView archive
30    31    X3.6  2005/09/09     808  09:42  09:59  10:08  MovieView archive
31    32    X3.6  2004/07/16     649  13:49  13:55  14:01  MovieView archive
32    33    X3.6  2003/05/28     365  00:17  00:27  00:39  MovieView archive
33    34    X3.4  2006/12/13     930  02:14  02:40  02:57  MovieView archive
34    35    X3.4  2001/12/28    9767  20:02  20:45  21:32  MovieView archive
35    36    X3.3  2013/11/05    1890  22:07  22:12  22:15  MovieView archive
36    37    X3.3  2002/07/20      39  21:04  21:30  21:54  MovieView archive
37    38    X3.3  1998/11/28    8395  04:54  05:52  06:13  MovieView archive
38    39    X3.2  2013/05/14    1748  00:00  01:11  01:20  MovieView archive
39    40    X3.1  2014/10/24    2192  21:07  21:41  22:13  MovieView archive
40    41    X3.1  2002/08/24      69  00:49  01:12  01:31  MovieView archive
41    42      X3  2002/07/15      30  19:59  20:08  20:14  MovieView archive
42    43    X2.8  2013/05/13    1748  15:48  16:05  16:16  MovieView archive
43    44    X2.8  2001/12/11    9733  07:58  08:08  08:14  MovieView archive
44    45    X2.8  1998/08/18    8307  08:14  08:24  08:32       View archive
45    46    X2.7  2015/05/05    2339  22:05  22:11  22:15  MovieView archive
46    47    X2.7  2003/11/03     488  01:09  01:30  01:45  MovieView archive
47    48    X2.7  1998/05/06    8210  07:58  08:09  08:20  MovieView archive
48    49    X2.6  2005/01/15     720  22:25  23:02  23:31  MovieView archive
49    50    X2.6  2001/09/24    9632  09:32  10:38  11:09  MovieView archive

In [214]:
# Drop the extra movie column
data = data.drop(columns = 'Unnamed: 7')

# To format into datetime, combine the date along with each time column 
data['Start_DT'] = pd.to_datetime(data['Date'] + ' ' + data['Start'])
data['Max_DT'] = pd.to_datetime(data['Date'] + ' ' + data['Max'])
data['End_DT'] = pd.to_datetime(data['Date'] + ' ' + data['End'])

In [215]:
# drop the uneccessary non-datetime columns
data = data.drop(columns=['Date', 'Start', 'Max', 'End'])

# Reorganized columns to match project description output 
data = data[['Rank', 'X_class', 'Start_DT', 'Max_DT', 'End_DT', 'Region']]
# Replace all missing data with NaN
data = data.replace('-', 'NaN')
data
# End of step 2

,Rank,X_class,Start_DT,Max_DT,End_DT,Region
0,1,X28+,2003-11-04 19:29:00,2003-11-04 19:53:00,2003-11-04 20:06:00,486
1,2,X20+,2001-04-02 21:32:00,2001-04-02 21:51:00,2001-04-02 22:03:00,9393
2,3,X17.2+,2003-10-28 09:51:00,2003-10-28 11:10:00,2003-10-28 11:24:00,486
3,4,X17+,2005-09-07 17:17:00,2005-09-07 17:40:00,2005-09-07 18:03:00,808
4,5,X14.4,2001-04-15 13:19:00,2001-04-15 13:50:00,2001-04-15 13:55:00,9415
5,6,X10,2003-10-29 20:37:00,2003-10-29 20:49:00,2003-10-29 21:01:00,486
6,7,X9.4,1997-11-06 11:49:00,1997-11-06 11:55:00,1997-11-06 12:01:00,8100
7,8,X9.3,2017-09-06 11:53:00,2017-09-06 12:02:00,2017-09-06 12:10:00,2673
8,9,X9,2006-12-05 10:18:00,2006-12-05 10:35:00,2006-12-05 10:45:00,930
9,10,X8.3,2003-11-02 17:03:00,2003-11-02 17:25:00,2003-11-02 17:39:00,486
10,11,X8.2,2017-09-10 15:35:00,2017-09-10 16:06:00,2017-09-10 16:31:00,2673
11,12,X7.1,2005-01-20 06:36:00,2005-01-20 07:01:00,2005-01-20 07:26:00,720
12,13,X6.9,2011-08-09 07:48:00,2011-08-09 08:05:00,2011-08-09 08:08:00,1263
13,14,X6.5,2006-12-06 18:29:00,2006-12-06 18:47:00,2006-12-06 19:00:00,930
14,15,X6.2,2005-09-09 19:13:00,2005-09-09 20:04:00,2005-09-09 20:36:00,808
15,16,X6.2,2001-12-13 14:20:00,2001-12-13 14:30:00,2001-12-13 14:35:00,9733
16,17,X5.7,2000-07-14 10:03:00,2000-07-14 10:24:00,2000-07-14 10:43:00,9077
17,18,X5.6,2001-04-06 19:10:00,2001-04-06 19:21:00,2001-04-06 19:31:00,9415
18,19,X5.4,2012-03-07 00:02:00,2012-03-07 00:24:00,2012-03-07 00:40:00,1429
19,20,X5.4,2005-09-08 20:52:00,2005-09-08 21:06:00,2005-09-08 21:17:00,808
20,21,X5.4,2003-10-23 08:19:00,2003-10-23 08:35:00,2003-10-23 08:49:00,486
21,22,X5.3,2001-08-25 16:23:00,2001-08-25 16:45:00,2001-08-25 17:04:00,9591
22,23,X4.9,2014-02-25 00:39:00,2014-02-25 00:49:00,2014-02-25 01:03:00,1990
23,24,X4.9,1998-08-18 22:10:00,1998-08-18 22:19:00,1998-08-18 22:28:00,8307
24,25,X4.8,2002-07-23 00:18:00,2002-07-23 00:35:00,2002-07-23 00:47:00,39
25,26,X4,2000-11-26 16:34:00,2000-11-26 16:48:00,2000-11-26 16:56:00,9236
26,27,X3.9,2003-11-03 09:43:00,2003-11-03 09:55:00,2003-11-03 10:19:00,488
27,28,X3.9,1998-08-19 21:35:00,1998-08-19 21:45:00,1998-08-19 21:50:00,8307
28,29,X3.8,2005-01-17 06:59:00,2005-01-17 09:52:00,2005-01-17 10:07:00,720
29,30,X3.7,1998-11-22 06:30:00,1998-11-22 06:42:00,1998-11-22 06:49:00,8384
30,31,X3.6,2005-09-09 09:42:00,2005-09-09 09:59:00,2005-09-09 10:08:00,808
31,32,X3.6,2004-07-16 13:49:00,2004-07-16 13:55:00,2004-07-16 14:01:00,649
32,33,X3.6,2003-05-28 00:17:00,2003-05-28 00:27:00,2003-05-28 00:39:00,365
33,34,X3.4,2006-12-13 02:14:00,2006-12-13 02:40:00,2006-12-13 02:57:00,930
34,35,X3.4,2001-12-28 20:02:00,2001-12-28 20:45:00,2001-12-28 21:32:00,9767
35,36,X3.3,2013-11-05 22:07:00,2013-11-05 22:12:00,2013-11-05 22:15:00,1890
36,37,X3.3,2002-07-20 21:04:00,2002-07-20 21:30:00,2002-07-20 21:54:00,39
37,38,X3.3,1998-11-28 04:54:00,1998-11-28 05:52:00,1998-11-28 06:13:00,8395
38,39,X3.2,2013-05-14 00:00:00,2013-05-14 01:11:00,2013-05-14 01:20:00,1748
39,40,X3.1,2014-10-24 21:07:00,2014-10-24 21:41:00,2014-10-24 22:13:00,2192
40,41,X3.1,2002-08-24 00:49:00,2002-08-24 01:12:00,2002-08-24 01:31:00,69
41,42,X3,2002-07-15 19:59:00,2002-07-15 20:08:00,2002-07-15 20:14:00,30
42,43,X2.8,2013-05-13 15:48:00,2013-05-13 16:05:00,2013-05-13 16:16:00,1748
43,44,X2.8,2001-12-11 07:58:00,2001-12-11 08:08:00,2001-12-11 08:14:00,9733
44,45,X2.8,1998-08-18 08:14:00,1998-08-18 08:24:00,1998-08-18 08:32:00,8307
45,46,X2.7,2015-05-05 22:05:00,2015-05-05 22:11:00,2015-05-05 22:15:00,2339
46,47,X2.7,2003-11-03 01:09:00,2003-11-03 01:30:00,2003-11-03 01:45:00,488
47,48,X2.7,1998-05-06 07:58:00,1998-05-06 08:09:00,1998-05-06 08:20:00,8210
48,49,X2.6,2005-01-15 22:25:00,2005-01-15 23:02:00,2005-01-15 23:31:00,720
49,50,X2.6,2001-09-24 09:32:00,2001-09-24 10:38:00,2001-09-24 11:09:00,9632

In [216]:
# Start of part 3. Use the same process at part1 to start
res = requests.get("https://cdaw.gsfc.nasa.gov/CME_list/radio/waves_type2.html")
soup = BeautifulSoup(res.content, "html.parser")
# print (soup.prettify)

In [217]:
# This link does NOT have a marked table. Must extract as text instead
nasa_tab = soup.find('pre')
txt = nasa_tab.get_text()
# txt

In [218]:
# Since each row of data appears on a new line, split this string by line
rows = txt.split('\n')

# Now remove the unnecessary beginning and ending lines
for i in range(12):
    rows.pop(0);
for i in range(2):
    rows.pop(len(rows) - 1)

# Create a table with the proper columns 
nasa_data = pd.DataFrame(columns=['Start_Date', 'Start_Time', 'End_Date', 'End_Time', 'Start_Freq', 
'End_Freq', 'Flare_Loc', 'Flare_Region','Flare_Class', 'CME_Date', 
'CME_Time', 'CME_Angle', 'CME_Width', 'CME_Speed', 'Plot'], index = range(0,len(rows)))

# Now load each line into the newly created dataframe
row_index = 0
for temp in rows:
    row = temp.split(' ')
    while '' in row:
        row.remove('')
    col_index = 0
    while col_index < 15:
        nasa_data.iat[row_index, col_index] = row[col_index]
        col_index += 1
    row_index += 1
nasa_data
# End of step 3

,Start_Date,Start_Time,End_Date,End_Time,Start_Freq,End_Freq,Flare_Loc,Flare_Region,Flare_Class,CME_Date,CME_Time,CME_Angle,CME_Width,CME_Speed,Plot
0,1997/04/01,14:00,04/01,14:15,8000,4000,S25E16,8026,M1.3,04/01,15:18,74,79,312,PHTX
1,1997/04/07,14:30,04/07,17:30,11000,1000,S28E19,8027,C6.8,04/07,14:27,Halo,360,878,PHTX
2,1997/05/12,05:15,05/14,16:00,12000,80,N21W08,8038,C1.3,05/12,05:30,Halo,360,464,PHTX
3,1997/05/21,20:20,05/21,22:00,5000,500,N05W12,8040,M1.3,05/21,21:00,263,165,296,PHTX
4,1997/09/23,21:53,09/23,22:16,6000,2000,S29E25,8088,C1.4,09/23,22:02,133,155,712,PHTX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,2017/09/17,11:45,09/17,12:35,16000,900,S08E170,-----,----,09/17,12:00,Halo,360,1385,PHTX
518,2017/10/18,05:48,10/18,12:40,16000,400,S06E123,-----,----,10/18,08:00,85,146,1001,PHTX
519,2019/05/03,23:52,05/04,00:16,13000,2300,N12E82,12740,C1.0,05/03,23:24,90,113,692,PHTX
520,2020/11/29,13:07,11/29,15:23,14000,850,S23E89,-----,M4.4,11/29,13:25,Halo,360,2077,----
521,2020/12/07,16:18,12/08,02:00,14000,160,S25W08,12790,C7.4,12/07,16:24,Halo,360,1407,----

In [219]:
# Start by recoding the dashes as NaN
nasa_data = nasa_data.replace('----', 'NaN')
nasa_data = nasa_data.replace('-----', 'NaN')
nasa_data = nasa_data.replace('????', 'NaN')
nasa_data = nasa_data.replace('--', 'NaN')
nasa_data = nasa_data.replace('--:--', 'NaN')
nasa_data = nasa_data.replace('--/--', 'NaN')

# Create new halo column and fill it with booleans checked against CME angles
nasa_data['Halo'] = nasa_data['CME_Angle'].map(lambda x: x == 'Halo')

# Replace Halos with NA in CME angle column
nasa_data = nasa_data.replace('Halo', "NA")

# Removing the > from the width columns and instead adding a col that determines lower bound
nasa_data['Lower_Bound'] = nasa_data['CME_Width'].map(lambda x: str(x).__contains__('>'))
nasa_data['CME_Width'] = nasa_data['CME_Width'].map(lambda x: x if str(x)[0] != '>' else str(x)[1:])

# Adjust rows to allow datetime formatting
nasa_data['Start_DT'] = pd.to_datetime(nasa_data['Start_Date'] + ' ' + nasa_data['Start_Time'])

# Prepend a year to the end dates and CME dates
for i in range(len(nasa_data.index)):
    temp = nasa_data.values[i][0].split('/')
    year = str(temp[0]) + '/'
    nasa_data.iat[i, 2] = year + nasa_data.iat[i, 2]
    nasa_data.iat[i,9] = year + nasa_data.iat[i,9]

# Set the end columns to datetime
nasa_data['End_Time'] = nasa_data['End_Time'].replace('24:00', '0:00')
nasa_data['End_DT'] = pd.to_datetime(nasa_data['End_Date'] + ' ' + nasa_data['End_Time'])

# Set the cme columns to datetime
nasa_data['CME_DT'] = ''
for i in range(len(nasa_data.index)):
    if nasa_data.iat[i,9] != 'NaN' and nasa_data.iat[i,10] != 'NaN':
       nasa_data.iat[i, 19] = pd.to_datetime(nasa_data.iat[i,9] + ' ' + nasa_data.iat[i,10])

# Drop and rearrange columns to match example 
nasa_data = nasa_data.drop(columns = ['Start_Date', 'Start_Time', 'End_Date', 'End_Time', 'CME_Date', 'CME_Time'])
nasa_data = nasa_data.rename(columns = {'Flare_Class': 'Importance', 'CME_Angle': 'Angle', 
                            'CME_Speed': 'Speed', 'CME_Width': 'Width'})
nasa_data = nasa_data[['Start_DT', 'End_DT', 'Start_Freq', 'End_Freq', 'Flare_Loc', 'Flare_Region', 
                       'Importance', 'CME_DT', 'Angle', 'Width', 'Speed', 'Plot', 'Halo', 'Lower_Bound']]
nasa_data
# End of step 4
# End of part 1

,Start_DT,End_DT,Start_Freq,End_Freq,Flare_Loc,Flare_Region,Importance,CME_DT,Angle,Width,Speed,Plot,Halo,Lower_Bound
0,1997-04-01 14:00:00,1997-04-01 14:15:00,8000,4000,S25E16,8026,M1.3,1997-04-01 15:18:00,74,79,312,PHTX,False,False
1,1997-04-07 14:30:00,1997-04-07 17:30:00,11000,1000,S28E19,8027,C6.8,1997-04-07 14:27:00,NA,360,878,PHTX,True,False
2,1997-05-12 05:15:00,1997-05-14 16:00:00,12000,80,N21W08,8038,C1.3,1997-05-12 05:30:00,NA,360,464,PHTX,True,False
3,1997-05-21 20:20:00,1997-05-21 22:00:00,5000,500,N05W12,8040,M1.3,1997-05-21 21:00:00,263,165,296,PHTX,False,False
4,1997-09-23 21:53:00,1997-09-23 22:16:00,6000,2000,S29E25,8088,C1.4,1997-09-23 22:02:00,133,155,712,PHTX,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,2017-09-17 11:45:00,2017-09-17 12:35:00,16000,900,S08E170,NaN,NaN,2017-09-17 12:00:00,NA,360,1385,PHTX,True,False
518,2017-10-18 05:48:00,2017-10-18 12:40:00,16000,400,S06E123,NaN,NaN,2017-10-18 08:00:00,85,146,1001,PHTX,False,False
519,2019-05-03 23:52:00,2019-05-04 00:16:00,13000,2300,N12E82,12740,C1.0,2019-05-03 23:24:00,90,113,692,PHTX,False,False
520,2020-11-29 13:07:00,2020-11-29 15:23:00,14000,850,S23E89,NaN,M4.4,2020-11-29 13:25:00,NA,360,2077,NaN,True,False
521,2020-12-07 16:18:00,2020-12-08 02:00:00,14000,160,S25W08,12790,C7.4,2020-12-07 16:24:00,NA,360,1407,NaN,True,False

In [220]:
# Isolate rows with max intensity flares 
# (only 50. Also technically already sorted at this point)
data = data.loc[data['X_class'].str.contains('X')]

# Remove X from classifications and sort as float
data['X_class'] = data['X_class'].str.lstrip('X')
data['X_class'] = data['X_class'].str.rstrip('+')
data['X_class'] = data.X_class.astype(float)
data = data.head(50).sort_values('X_class', ascending= False)

# Add the X back on for later comparision in part 2
data['X_class'] = data.X_class.astype(str)
data['X_class'] = 'X' + data['X_class']

data

,Rank,X_class,Start_DT,Max_DT,End_DT,Region
0,1,X28.0,2003-11-04 19:29:00,2003-11-04 19:53:00,2003-11-04 20:06:00,486
1,2,X20.0,2001-04-02 21:32:00,2001-04-02 21:51:00,2001-04-02 22:03:00,9393
2,3,X17.2,2003-10-28 09:51:00,2003-10-28 11:10:00,2003-10-28 11:24:00,486
3,4,X17.0,2005-09-07 17:17:00,2005-09-07 17:40:00,2005-09-07 18:03:00,808
4,5,X14.4,2001-04-15 13:19:00,2001-04-15 13:50:00,2001-04-15 13:55:00,9415
5,6,X10.0,2003-10-29 20:37:00,2003-10-29 20:49:00,2003-10-29 21:01:00,486
6,7,X9.4,1997-11-06 11:49:00,1997-11-06 11:55:00,1997-11-06 12:01:00,8100
7,8,X9.3,2017-09-06 11:53:00,2017-09-06 12:02:00,2017-09-06 12:10:00,2673
8,9,X9.0,2006-12-05 10:18:00,2006-12-05 10:35:00,2006-12-05 10:45:00,930
9,10,X8.3,2003-11-02 17:03:00,2003-11-02 17:25:00,2003-11-02 17:39:00,486
10,11,X8.2,2017-09-10 15:35:00,2017-09-10 16:06:00,2017-09-10 16:31:00,2673
11,12,X7.1,2005-01-20 06:36:00,2005-01-20 07:01:00,2005-01-20 07:26:00,720
12,13,X6.9,2011-08-09 07:48:00,2011-08-09 08:05:00,2011-08-09 08:08:00,1263
13,14,X6.5,2006-12-06 18:29:00,2006-12-06 18:47:00,2006-12-06 19:00:00,930
14,15,X6.2,2005-09-09 19:13:00,2005-09-09 20:04:00,2005-09-09 20:36:00,808
15,16,X6.2,2001-12-13 14:20:00,2001-12-13 14:30:00,2001-12-13 14:35:00,9733
16,17,X5.7,2000-07-14 10:03:00,2000-07-14 10:24:00,2000-07-14 10:43:00,9077
17,18,X5.6,2001-04-06 19:10:00,2001-04-06 19:21:00,2001-04-06 19:31:00,9415
18,19,X5.4,2012-03-07 00:02:00,2012-03-07 00:24:00,2012-03-07 00:40:00,1429
19,20,X5.4,2005-09-08 20:52:00,2005-09-08 21:06:00,2005-09-08 21:17:00,808
20,21,X5.4,2003-10-23 08:19:00,2003-10-23 08:35:00,2003-10-23 08:49:00,486
21,22,X5.3,2001-08-25 16:23:00,2001-08-25 16:45:00,2001-08-25 17:04:00,9591
22,23,X4.9,2014-02-25 00:39:00,2014-02-25 00:49:00,2014-02-25 01:03:00,1990
23,24,X4.9,1998-08-18 22:10:00,1998-08-18 22:19:00,1998-08-18 22:28:00,8307
24,25,X4.8,2002-07-23 00:18:00,2002-07-23 00:35:00,2002-07-23 00:47:00,39
25,26,X4.0,2000-11-26 16:34:00,2000-11-26 16:48:00,2000-11-26 16:56:00,9236
26,27,X3.9,2003-11-03 09:43:00,2003-11-03 09:55:00,2003-11-03 10:19:00,488
27,28,X3.9,1998-08-19 21:35:00,1998-08-19 21:45:00,1998-08-19 21:50:00,8307
28,29,X3.8,2005-01-17 06:59:00,2005-01-17 09:52:00,2005-01-17 10:07:00,720
29,30,X3.7,1998-11-22 06:30:00,1998-11-22 06:42:00,1998-11-22 06:49:00,8384
30,31,X3.6,2005-09-09 09:42:00,2005-09-09 09:59:00,2005-09-09 10:08:00,808
31,32,X3.6,2004-07-16 13:49:00,2004-07-16 13:55:00,2004-07-16 14:01:00,649
32,33,X3.6,2003-05-28 00:17:00,2003-05-28 00:27:00,2003-05-28 00:39:00,365
33,34,X3.4,2006-12-13 02:14:00,2006-12-13 02:40:00,2006-12-13 02:57:00,930
34,35,X3.4,2001-12-28 20:02:00,2001-12-28 20:45:00,2001-12-28 21:32:00,9767
35,36,X3.3,2013-11-05 22:07:00,2013-11-05 22:12:00,2013-11-05 22:15:00,1890
36,37,X3.3,2002-07-20 21:04:00,2002-07-20 21:30:00,2002-07-20 21:54:00,39
37,38,X3.3,1998-11-28 04:54:00,1998-11-28 05:52:00,1998-11-28 06:13:00,8395
38,39,X3.2,2013-05-14 00:00:00,2013-05-14 01:11:00,2013-05-14 01:20:00,1748
39,40,X3.1,2014-10-24 21:07:00,2014-10-24 21:41:00,2014-10-24 22:13:00,2192
40,41,X3.1,2002-08-24 00:49:00,2002-08-24 01:12:00,2002-08-24 01:31:00,69
41,42,X3.0,2002-07-15 19:59:00,2002-07-15 20:08:00,2002-07-15 20:14:00,30
42,43,X2.8,2013-05-13 15:48:00,2013-05-13 16:05:00,2013-05-13 16:16:00,1748
43,44,X2.8,2001-12-11 07:58:00,2001-12-11 08:08:00,2001-12-11 08:14:00,9733
44,45,X2.8,1998-08-18 08:14:00,1998-08-18 08:24:00,1998-08-18 08:32:00,8307
45,46,X2.7,2015-05-05 22:05:00,2015-05-05 22:11:00,2015-05-05 22:15:00,2339
46,47,X2.7,2003-11-03 01:09:00,2003-11-03 01:30:00,2003-11-03 01:45:00,488
47,48,X2.7,1998-05-06 07:58:00,1998-05-06 08:09:00,1998-05-06 08:20:00,8210
48,49,X2.6,2005-01-15 22:25:00,2005-01-15 23:02:00,2005-01-15 23:31:00,720
49,50,X2.6,2001-09-24 09:32:00,2001-09-24 10:38:00,2001-09-24 11:09:00,9632

In [221]:
# Now do the same for the NASA data 
n_top = nasa_data.loc[nasa_data['Importance'].str.contains('X')].copy(deep= True)

# Remove X from classifications and sort as float
n_top['Importance'] = n_top['Importance'].str.lstrip('X')
n_top['Importance'] = n_top['Importance'].str.rstrip('+')
n_top['Importance'] = n_top.Importance.astype(float)
n_top = n_top.head(50).sort_values('Importance', ascending= False)

# Add the X back on, will be useful in part 2
n_top['Importance'] = n_top.Importance.astype(str)
n_top['Importance'] = 'X' + n_top['Importance']
n_top

,Start_DT,End_DT,Start_Freq,End_Freq,Flare_Loc,Flare_Region,Importance,CME_DT,Angle,Width,Speed,Plot,Halo,Lower_Bound
117,2001-04-02 22:05:00,2001-04-03 02:30:00,14000,250,N19W72,9393,X20.0,2001-04-02 22:06:00,261,244,2505,PHTX,False,False
233,2003-10-28 11:10:00,2003-10-29 00:00:00,14000,40,S16E08,10486,X17.0,2003-10-28 11:30:00,NA,360,2459,PHTX,True,False
126,2001-04-15 14:05:00,2001-04-16 13:00:00,14000,40,S20W85,9415,X14.0,2001-04-15 14:06:00,245,167,1199,PHTX,False,False
234,2003-10-29 20:55:00,2003-10-29 00:00:00,11000,500,S15W02,10486,X10.0,2003-10-29 20:54:00,NA,360,2029,PHTX,True,False
8,1997-11-06 12:20:00,1997-11-07 08:30:00,14000,100,S18W63,8100,X9.4,1997-11-06 12:10:00,NA,360,1556,PHTX,True,False
237,2003-11-02 17:30:00,2003-11-03 01:00:00,12000,250,S14W56,10486,X8.3,2003-11-02 17:30:00,NA,360,2598,PHTX,True,False
82,2000-07-14 10:30:00,2000-07-15 14:30:00,14000,80,N22W07,9077,X5.7,2000-07-14 10:54:00,NA,360,1674,PHTX,True,False
121,2001-04-06 19:35:00,2001-04-07 01:50:00,14000,230,S21E31,9415,X5.6,2001-04-06 19:30:00,NA,360,1270,PHTX,True,False
135,2001-08-25 16:50:00,2001-08-25 23:00:00,8000,170,S17E34,9591,X5.3,2001-08-25 16:50:00,NA,360,1433,PHTX,True,False
193,2002-07-23 00:50:00,2002-07-23 04:00:00,11000,400,S13E72,10039,X4.8,2002-07-23 00:42:00,NA,360,2285,PHTX,True,False
104,2000-11-26 17:00:00,2000-11-26 17:15:00,14000,7000,N18W38,9236,X4.0,2000-11-26 17:06:00,NA,360,980,PHTX,True,False
222,2003-05-28 01:00:00,2003-05-29 00:30:00,1000,200,S07W20,10365,X3.6,2003-05-28 00:50:00,NA,360,1366,PHTX,True,False
160,2001-12-28 20:35:00,2001-12-29 03:00:00,14000,350,S26E90,9756,X3.4,2001-12-28 20:30:00,NA,360,2216,PHTX,True,False
192,2002-07-20 21:30:00,2002-07-20 22:20:00,10000,2000,S13E90,10039,X3.3,2002-07-20 22:06:00,NA,360,1941,PHTX,True,False
201,2002-08-24 01:45:00,2002-08-24 03:25:00,5000,400,S02W81,10069,X3.1,2002-08-24 01:27:00,NA,360,1913,PHTX,True,False
238,2003-11-03 01:15:00,2003-11-03 01:25:00,3000,1500,N10W83,10488,X2.7,2003-11-03 01:59:00,304,65,827,PHTX,False,False
19,1998-05-06 08:25:00,1998-05-06 08:35:00,14000,5000,S11W65,8210,X2.7,1998-05-06 08:29:00,309,190,1099,PHTX,False,False
9,1997-11-27 13:30:00,1997-11-27 14:00:00,14000,7000,N17E63,8113,X2.6,1997-11-27 13:56:00,98,91,441,PHTX,False,False
142,2001-09-24 10:45:00,2001-09-25 20:00:00,7000,30,S16E23,9632,X2.6,2001-09-24 10:30:00,NA,360,2402,PHTX,True,False
73,2000-06-06 15:20:00,2000-06-08 09:00:00,14000,40,N20E18,9026,X2.3,2000-06-06 15:54:00,NA,360,1119,PHTX,True,False
99,2000-11-24 15:25:00,2000-11-24 22:00:00,14000,200,N22W07,9236,X2.3,2000-11-24 15:30:00,NA,360,1245,PHTX,True,False
123,2001-04-10 05:24:00,2001-04-10 00:00:00,14000,100,S23W09,9415,X2.3,2001-04-10 05:30:00,NA,360,2411,PHTX,True,False
7,1997-11-04 06:00:00,1997-11-05 04:30:00,14000,100,S14W33,8100,X2.1,1997-11-04 06:10:00,NA,360,785,PHTX,True,False
98,2000-11-24 05:10:00,2000-11-24 15:00:00,14000,100,N20W05,9236,X2.0,2000-11-24 05:30:00,NA,360,1289,PHTX,True,False
125,2001-04-12 10:20:00,2001-04-12 10:40:00,14000,7000,S19W43,9415,X2.0,2001-04-12 10:31:00,NA,360,1184,PHTX,True,False
102,2000-11-25 19:00:00,2000-11-25 19:35:00,6000,2000,N20W23,9236,X1.9,2000-11-25 19:31:00,NA,360,671,PHTX,True,False
189,2002-07-18 07:55:00,2002-07-18 08:45:00,14000,1500,N19W30,10030,X1.8,2002-07-18 08:06:00,NA,360,1099,PHTX,True,False
100,2000-11-24 22:24:00,2000-11-24 22:36:00,4000,3000,N21W14,9236,X1.8,2000-11-24 22:06:00,NA,360,1005,PHTX,True,False
49,1999-10-14 09:10:00,1999-10-14 10:00:00,14000,4000,N11E32,8731,X1.8,1999-10-14 09:26:00,NA,360,1250,PHTX,True,False
115,2001-03-29 10:12:00,2001-03-30 06:00:00,4000,60,N20W19,9393,X1.7,2001-03-29 10:26:00,NA,360,942,PHTX,True,False
149,2001-10-19 01:15:00,2001-10-19 02:25:00,14000,1300,N16W18,9661,X1.6,2001-10-19 01:27:00,NA,360,558,PHTX,True,False
150,2001-10-19 16:45:00,2001-10-21 16:40:00,14000,30,N15W29,9661,X1.6,2001-10-19 16:50:00,NA,360,901,PHTX,True,False
217,2003-03-18 12:25:00,2003-03-18 13:45:00,4500,500,S15W46,10314,X1.5,2003-03-18 12:30:00,263,209,1601,PHTX,False,False
178,2002-04-21 01:30:00,2002-04-21 00:00:00,10000,60,S14W84,9906,X1.5,2002-04-21 01:27:00,NA,360,2393,PHTX,True,False
226,2003-06-16 00:00:00,2003-06-16 03:00:00,14000,400,S07E80,10386,X1.3,2003-06-15 23:54:00,NA,360,2053,PHTX,True,False
152,2001-10-25 15:30:00,2001-10-27 23:00:00,14000,30,S16W21,9672,X1.3,2001-10-25 15:26:00,NA,360,1092,PHTX,True,False
221,2003-05-27 23:12:00,2003-05-27 23:45:00,14000,2000,S07W17,10365,X1.3,2003-05-27 23:50:00,NA,360,964,PHTX,True,False
55,2000-02-05 19:34:00,2000-02-05 19:38:00,5800,2900,N26E52,8858,X1.2,2000-02-05 19:54:00,60,76,632,PHTX,False,False
14,1998-04-23 06:00:00,1998-04-23 15:30:00,14000,200,S17E90,8210,X1.2,1998-04-23 05:55:00,NA,360,1691,PHTX,True,False
232,2003-10-26 17:45:00,2003-10-26 19:40:00,14000,1500,N02W38,10484,X1.2,2003-10-26 17:54:00,270,171,1537,PHTX,False,True
118,2001-04-03 03:40:00,2001-04-03 07:25:00,14000,400,S21E83,9415,X1.2,2001-04-03 03:26:00,108,292,1613,PHTX,False,False
231,2003-10-26 07:00:00,2003-10-26 09:15:00,8000,1500,S15E44,10486,X1.2,2003-10-26 06:54:00,108,207,1371,PHTX,False,True
223,2003-05-29 01:10:00,2003-05-29 08:00:00,13000,200,S06W37,10365,X1.2,2003-05-29 01:27:00,NA,360,1237,PHTX,True,False
116,2001-04-02 11:30:00,2001-04-02 12:00:00,14000,5000,N20W70,9393,X1.1,2001-04-02 11:26:00,270,80,992,PHTX,False,False
18,1998-05-02 14:25:00,1998-05-02 14:50:00,5000,3000,S15W15,8210,X1.1,1998-05-02 14:06:00,NA,360,938,PHTX,True,False
46,1999-08-28 18:25:00,1999-08-28 18:33:00,16000,12000,S26W14,8674,X1.1,1999-08-28 18:26:00,120,245,462,PHTX,False,False
196,2002-08-03 19:20:00,2002-08-03 20:30:00,14000,2000,S16W76,10039,X1.0,2002-08-03 19:31:00,259,138,1150,PHTX,False,False
16,1998-04-27 09:20:00,1998-04-27 10:00:00,10000,1000,S16E50,8210,X1.0,1998-04-27 08:56:00,NA,360,1385,PHTX,True,False
153,2001-11-04 16:30:00,2001-11-06 11:00:00,14000,70,N06W18,9684,X1.0,2001-11-04 16:35:00,NA,360,1810,PHTX,True,False
80,2000-07-11 13:00:00,2000-07-11 13:30:00,12000,1000,N18E27,9077,X1.0,2000-07-11 13:27:00,NA,360,1078,PHTX,True,False

In [222]:
# The data is replicable. Many of the highest intensity flares are shown in both tables
# along with similar regions even though the time is a little off

# End of step 1

In [223]:
# For step 2, I define a matching row as one that has the same intensity (x-class)
# and the same region. Also wanted to use time but the minutes are all off 

# Create new column for rows that match
nasa_data['SW_Rank'] = 'NaN'

# Create fxn 
def matcher(index):
    for temp, row in data.iterrows():
        # First check the classifications
        if nasa_data.iat[index, 6] == row[1]:
            # Now check the region
            if float((nasa_data.iat[index,5])[-4:]) == float(row[5]):
                # If match, then return the rank from the sw data
                return row['Rank']
    return 'NaN'

# Apply the matcher to each row in the nasa table and adjust the new column 
for i,row2 in nasa_data.iterrows():
    nasa_data.iat[i,14] = matcher(i)

nasa_data

,Start_DT,End_DT,Start_Freq,End_Freq,Flare_Loc,Flare_Region,Importance,CME_DT,Angle,Width,Speed,Plot,Halo,Lower_Bound,SW_Rank
0,1997-04-01 14:00:00,1997-04-01 14:15:00,8000,4000,S25E16,8026,M1.3,1997-04-01 15:18:00,74,79,312,PHTX,False,False,NaN
1,1997-04-07 14:30:00,1997-04-07 17:30:00,11000,1000,S28E19,8027,C6.8,1997-04-07 14:27:00,NA,360,878,PHTX,True,False,NaN
2,1997-05-12 05:15:00,1997-05-14 16:00:00,12000,80,N21W08,8038,C1.3,1997-05-12 05:30:00,NA,360,464,PHTX,True,False,NaN
3,1997-05-21 20:20:00,1997-05-21 22:00:00,5000,500,N05W12,8040,M1.3,1997-05-21 21:00:00,263,165,296,PHTX,False,False,NaN
4,1997-09-23 21:53:00,1997-09-23 22:16:00,6000,2000,S29E25,8088,C1.4,1997-09-23 22:02:00,133,155,712,PHTX,False,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,2017-09-17 11:45:00,2017-09-17 12:35:00,16000,900,S08E170,NaN,NaN,2017-09-17 12:00:00,NA,360,1385,PHTX,True,False,NaN
518,2017-10-18 05:48:00,2017-10-18 12:40:00,16000,400,S06E123,NaN,NaN,2017-10-18 08:00:00,85,146,1001,PHTX,False,False,NaN
519,2019-05-03 23:52:00,2019-05-04 00:16:00,13000,2300,N12E82,12740,C1.0,2019-05-03 23:24:00,90,113,692,PHTX,False,False,NaN
520,2020-11-29 13:07:00,2020-11-29 15:23:00,14000,850,S23E89,NaN,M4.4,2020-11-29 13:25:00,NA,360,2077,NaN,True,False,NaN
521,2020-12-07 16:18:00,2020-12-08 02:00:00,14000,160,S25W08,12790,C7.4,2020-12-07 16:24:00,NA,360,1407,NaN,True,False,NaN

In [225]:
# Check to make sure the last cell actually made modifications
checker = nasa_data.loc[~(nasa_data['SW_Rank'] == 'NaN')]
checker

# End of question 3

,Start_DT,End_DT,Start_Freq,End_Freq,Flare_Loc,Flare_Region,Importance,CME_DT,Angle,Width,Speed,Plot,Halo,Lower_Bound,SW_Rank
8,1997-11-06 12:20:00,1997-11-07 08:30:00,14000,100,S18W63,8100,X9.4,1997-11-06 12:10:00,NA,360,1556,PHTX,True,False,7
19,1998-05-06 08:25:00,1998-05-06 08:35:00,14000,5000,S11W65,8210,X2.7,1998-05-06 08:29:00,309,190,1099,PHTX,False,False,48
82,2000-07-14 10:30:00,2000-07-15 14:30:00,14000,80,N22W07,9077,X5.7,2000-07-14 10:54:00,NA,360,1674,PHTX,True,False,17
104,2000-11-26 17:00:00,2000-11-26 17:15:00,14000,7000,N18W38,9236,X4.0,2000-11-26 17:06:00,NA,360,980,PHTX,True,False,26
121,2001-04-06 19:35:00,2001-04-07 01:50:00,14000,230,S21E31,9415,X5.6,2001-04-06 19:30:00,NA,360,1270,PHTX,True,False,18
135,2001-08-25 16:50:00,2001-08-25 23:00:00,8000,170,S17E34,9591,X5.3,2001-08-25 16:50:00,NA,360,1433,PHTX,True,False,22
142,2001-09-24 10:45:00,2001-09-25 20:00:00,7000,30,S16E23,9632,X2.6,2001-09-24 10:30:00,NA,360,2402,PHTX,True,False,50
192,2002-07-20 21:30:00,2002-07-20 22:20:00,10000,2000,S13E90,10039,X3.3,2002-07-20 22:06:00,NA,360,1941,PHTX,True,False,37
193,2002-07-23 00:50:00,2002-07-23 04:00:00,11000,400,S13E72,10039,X4.8,2002-07-23 00:42:00,NA,360,2285,PHTX,True,False,25
201,2002-08-24 01:45:00,2002-08-24 03:25:00,5000,400,S02W81,10069,X3.1,2002-08-24 01:27:00,NA,360,1913,PHTX,True,False,41
222,2003-05-28 01:00:00,2003-05-29 00:30:00,1000,200,S07W20,10365,X3.6,2003-05-28 00:50:00,NA,360,1366,PHTX,True,False,33
237,2003-11-02 17:30:00,2003-11-03 01:00:00,12000,250,S14W56,10486,X8.3,2003-11-02 17:30:00,NA,360,2598,PHTX,True,False,10
238,2003-11-03 01:15:00,2003-11-03 01:25:00,3000,1500,N10W83,10488,X2.7,2003-11-03 01:59:00,304,65,827,PHTX,False,False,47
239,2003-11-03 10:00:00,2003-11-03 12:30:00,6000,400,N08W77,10488,X3.9,2003-11-03 10:06:00,293,103,1420,PHTX,False,False,27
284,2005-01-15 23:00:00,2005-01-17 00:00:00,3000,40,N15W05,10720,X2.6,2005-01-15 23:06:00,NA,360,2861,PHTX,True,False,49
286,2005-01-17 10:00:00,2005-01-17 10:35:00,6100,1500,N15W25,10720,X3.8,2005-01-17 09:54:00,NA,360,2547,PHTX,True,False,29
288,2005-01-20 07:15:00,2005-01-20 16:30:00,14000,25,N14W61,10720,X7.1,2005-01-20 06:54:00,NA,360,882,PHTX,True,False,12
317,2005-09-09 19:45:00,2005-09-09 22:00:00,10000,50,S12E67,10808,X6.2,2005-09-09 19:48:00,NA,360,2257,PHTX,True,False,15
328,2006-12-05 10:50:00,2006-12-05 20:00:00,14000,250,S07E68,10930,X9.0,,NaN,NaN,NaN,PHTX,False,False,9
331,2006-12-06 19:00:00,2006-12-08 00:00:00,16000,30,S05E64,10930,X6.5,,NaN,NaN,NaN,PHTX,False,False,14
332,2006-12-13 02:45:00,2006-12-13 10:40:00,12000,150,S06W23,10930,X3.4,2006-12-13 02:54:00,NA,360,1774,PHTX,True,False,34
359,2011-08-09 08:20:00,2011-08-09 08:35:00,16000,4000,N17W69,11263,X6.9,2011-08-09 08:12:00,NA,360,1610,PHTX,True,False,13
375,2012-03-07 01:00:00,2012-03-08 19:00:00,16000,30,N17E27,11429,X5.4,2012-03-07 00:24:00,NA,360,2684,PHTX,True,False,19
403,2013-05-13 16:15:00,2013-05-13 19:10:00,16000,300,N11E85,11748,X2.8,2013-05-13 16:07:00,NA,360,1850,PHTX,True,False,43
404,2013-05-14 01:16:00,2013-05-14 08:20:00,16000,240,N08E77,11748,X3.2,2013-05-14 01:25:00,NA,360,2625,PHTX,True,False,39
443,2014-02-25 00:56:00,2014-02-25 11:28:00,14000,100,S12E82,11990,X4.9,2014-02-25 01:25:00,NA,360,2147,PHTX,True,False,23
487,2015-05-05 22:24:00,2015-05-05 23:14:00,14000,500,N15E79,12339,X2.7,2015-05-05 22:24:00,NA,360,715,PHTX,True,False,46
514,2017-09-06 12:05:00,2017-09-07 08:00:00,16000,70,S08W33,12673,X9.3,2017-09-06 12:24:00,NA,360,1571,PHTX,True,False,8